TRAIN:
  WARMUP_EPOCHS: 5
  EPOCHS: 300
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.05
AUG:
  SSL_AUG: True
MODEL:
  TYPE: mss
  NAME: mss_demo
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 6, 2 ]
    NUM_HEADS: [3, 6, 12, 24 ]
    WINDOW_SIZE: 7
  MSS:
    IS_MASK: True
    MASK_RATIO: 0.75
  MOBY:
    ENCODER: swin_mss
    ONLINE_DROP_PATH_RATE: 0.2